web/tracker/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from . import views

app_name = "tracker"

task_fields_patterns = [
    url(r'^executor/add/$', views.add_executor, name='executor_add'),
    url(r'^executor/(?P<executor_id>\d+)/delete/$', views.delete_executor, name='executor_delete'),

    url(r'^notification/add/$', views.add_notification, name='notification_add'),
    url(r'^notification/(?P<notification_id>\d+)/delete/$', views.delete_notification, name='notification_delete'),

    url(r'^tag/add/$', views.add_tag, name='tag_add'),
    url(r'^tag/(?P<tag_id>\d+)/delete/$', views.delete_task_tag, name='task_tag_delete'),

    url(r'^subtask/attach/$', views.attach_subtask, name='subtask_attach'),
    url(r'^subtask/(?P<subtask_id>\d+)/detach/$', views.detach_subtask, name='subtask_detach'),
]

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^users/singup/$', views.signup, name='signup'),
    url(r'^users/login/$', auth_views.login, name='login'),
    url(r'^users/logout/$', auth_views.logout, {'template_name': 'registration/logout.html'}, name='logout'),

    url(r'^search/task/$', views.search_task, name='task_search'),

    url(r'^tag/(?P<tag_id>\d+)/show/$', views.show_tag, name='tag_show'),
    url(r'^tag/(?P<tag_id>\d+)/edit/$', views.edit_tag, name='tag_edit'),
    url(r'^tag/(?P<tag_id>\d+)/delete/$', views.delete_tag, name='tag_delete'),

    url(r'^folder/add/$', views.add_folder, name='folder_add'),
    url(r'^folder/(?P<folder_id>[0-9]+)/edit/$', views.edit_folder, name='folder_edit'),
    url(r'^folder/(?P<folder_id>[0-9]+)/delete/$', views.delete_folder, name='folder_delete'),

    url(r'^planner/list/$', views.planner_list, name='planner_list'),
    url(r'^planner/add/$', views.add_planner, name='planner_add'),
    url(r'^planner/(?P<planner_id>[0-9]+)/delete/$', views.delete_planner, name='planner_delete'),
    url(r'^planner/(?P<planner_id>[0-9]+)/edit/$', views.edit_planner, name='planner_edit'),
    url(r'^planner/(?P<planner_id>[0-9]+)/show/$', views.show_planner, name='planner_show'),

    url(r'^folder/(?P<folder>[a-z0-9]+)/task/list/$', views.list_task, name='task_list'),
    url(r'^folder/(?P<folder>[a-z0-9]+)/task/add/$', views.add_task, name='task_add'),
    url(r'^folder/(?P<folder>[a-z0-9]+)/task/(?P<task_id>\d+)/', include(task_fields_patterns)),
    url(r'^folder/(?P<folder>[a-z0-9]+)/task/(?P<task_id>\d+)/edit/$', views.edit_task, name='task_edit'),
    url(r'^folder/(?P<folder>[a-z0-9]+)/task/(?P<task_id>\d+)/show/$', views.show_task, name='task_show'),
    url(r'^folder/(?P<folder>[a-z0-9]+)/task/(?P<task_id>\d+)/delete/$', views.delete_task, name='task_delete'),
    url(r'^folder/(?P<folder>[a-z0-9]+)/task/(?P<task_id>\d+)/complete/$', views.complete_task, name='task_complete'),
]

web/web/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('tracker.urls')),
]

web/tracker/models.py
from django.db import models

# Create your models here.

web/tracker/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from task_tracker_lib.models.task import Status, Priority
from task_tracker_lib.models.planner import IntervalType
from task_tracker_lib.api.exceptions import (
    TrackerLibraryError,
    AttachError,
    DetachError
)
from tracker import get_library_interface
from .handlers import (
    error_handler,
    check_planners,
    check_notifications
)
from .forms import (
    TaskForm, 
    FolderForm, 
    ExecutorForm,
    NotificatonForm,
    TagForm,
    PlannerForm,
    SubtaskForm,
    TaskSearchForm
)


@check_planners
@check_notifications
def home(request):
    return render(request, 'tracker/index.html')


@check_planners
@check_notifications
def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('tracker:home')
    else:
        form = UserCreationForm()

    return render(request, 
                  'registration/signup.html', 
                  {'form': form})


@login_required
@check_planners
@check_notifications
def list_task(request, folder):
    library_interface = get_library_interface()
    user = request.user.username

    if folder == "without":
        tasks = library_interface.get_tasks(user,
                                            without_folder=True,
                                            without_parent_task=True,
                                            status=Status.IN_PROGRESS)
        tasks.extend(library_interface.get_tasks(user,
                                                 without_folder=True,
                                                 without_parent_task=True,
                                                 status=Status.TODO))
    elif folder == "archive":
        tasks = library_interface.get_tasks(user, 
                                            status=Status.FAILED,
                                            without_parent_task=True)
        tasks.extend(library_interface.get_tasks(user, 
                                                 status=Status.DONE,
                                                 without_parent_task=True))
    elif folder == "executor":
        tasks = library_interface.get_tasks(user, 
                                            as_executor=True, 
                                            without_parent_task=True)
    elif folder.isdigit() and int(folder) != 0:
        folder_id = int(folder)
        tasks = library_interface.get_tasks(user,
                                            folder_id=folder_id,
                                            without_parent_task=True,
                                            status=Status.IN_PROGRESS)
        tasks.extend(library_interface.get_tasks(user,
                                                 folder_id=folder_id,
                                                 without_parent_task=True,
                                                 status=Status.TODO))

    folders = library_interface.get_folders(user)
    return render(request, 
                  'tracker/tasks/list.html', 
                  {'tasks': tasks,
                   'folders': folders,
                   'folder': folder})


@login_required
@error_handler
@check_planners
@check_notifications
def add_task(request, folder):
    library_interface = get_library_interface()
    user = request.user.username

    if request.method == 'POST':
        form = TaskForm(user, None, request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            priority = Priority(int(form.cleaned_data['priority']))
            description = form.cleaned_data['description']
            folder_id = int(form.cleaned_data['folder_id'])

            start_time = form.cleaned_data['start_time']
            if start_time is not None:
                start_time = start_time.replace(tzinfo=None)
            end_time = form.cleaned_data['end_time']
            if end_time is not None:
                end_time = end_time.replace(tzinfo=None)

            try:
                task_id = library_interface.create_task(
                    user, name, start_time, end_time,
                    priority, description
                )
                if folder_id != 0:
                    library_interface.add_task_to_folder(
                        user, task_id, folder_id)
            except TrackerLibraryError as e:
                form.add_error(None, str(e))
                return render(request, 
                              'tracker/tasks/add.html', 
                              {'form': form})

            folder = "without" if folder_id == 0 else folder_id
            return redirect('tracker:task_show', folder, task_id)
    else:
        form = TaskForm(
            user, None, 
            initial={
                'folder_id': 0 if folder == "without" else folder
            })

    return render(request, 'tracker/tasks/add.html', {'form': form})


@login_required
@error_handler
@check_planners
@check_notifications
def edit_task(request, folder, task_id):
    library_interface = get_library_interface()
    user = request.user.username

    if request.method == 'POST':
        form = TaskForm(user, task_id, request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            priority = Priority(int(form.cleaned_data['priority']))
            description = form.cleaned_data['description']
            folder_id = int(form.cleaned_data['folder_id'])

            start_time = form.cleaned_data['start_time']
            if start_time is not None:
                start_time = start_time.replace(tzinfo=None)
            end_time = form.cleaned_data['end_time']
            if end_time is not None:
                end_time = end_time.replace(tzinfo=None)

            try:
                library_interface.edit_task(
                    user, task_id, name, start_time, 
                    end_time, priority, description
                )
                if folder_id != -1: # if folder has not changed
                    if folder_id == 0:
                        library_interface.delete_task_from_folder(
                            user, task_id)
                        folder = "without"
                    else:
                        library_interface.add_task_to_folder(
                            user, task_id, folder_id)
                        folder = folder_id
            except (AttachError, DetachError) as e:
                form.add_error('folder_id', str(e))
                return render(request, 
                              'tracker/tasks/edit.html', 
                              {'form': form})
            except TrackerLibraryError as e:
                form.add_error(None, str(e))
                return render(request, 
                              'tracker/tasks/edit.html', 
                              {'form': form})

            return redirect('tracker:task_show', folder, task_id)
    else:
        task = library_interface.get_task(user, task_id)
        form = TaskForm(
            user, task_id,
            initial={
                'name': task.name,
                'start_time': task.start_time,
                'end_time': task.end_time,
                'priority': task.priority.value,
                'description': task.description
            }
        )

    return render(request, 'tracker/tasks/edit.html', {'form': form})


@login_required
@error_handler
@check_planners
@check_notifications
def delete_task(request, folder, task_id):
    if request.method == 'POST':
        library_interface = get_library_interface()
        user = request.user.username

        library_interface.delete_task(user, task_id, with_task_tree=True)
    return redirect('tracker:task_list', folder)


@login_required
@error_handler
@check_planners
@check_notifications
def show_task(request, folder, task_id):
    library_interface = get_library_interface()
    user = request.user.username

    if folder != 'executor':
        task = library_interface.get_task(user, task_id)
    else:
        task = library_interface.get_task(user, task_id, as_executor=True)
    return render(request, 
                  'tracker/tasks/show.html', 
                  {'folder':folder, 'task': task})


@login_required
@error_handler
@check_planners
@check_notifications
def complete_task(request, folder, task_id):
    if request.method == 'POST':
        library_interface = get_library_interface()
        user = request.user.username

        library_interface.complete_task(user, task_id)
    return redirect('tracker:task_list', folder)


@login_required
@error_handler
@check_planners
@check_notifications
def delete_folder(request, folder_id):
    library_interface = get_library_interface()
    user = request.user.username

    library_interface.delete_folder(user, folder_id)

    return redirect('tracker:task_list', folder='without')


@login_required
@check_planners
@check_notifications
def add_folder(request):
    library_interface = get_library_interface()
    user = request.user.username

    if request.method == 'POST':
        form = FolderForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']

            try:
                library_interface.add_folder(user, name)
            except ValueError as e:
                form.add_error('name', str(e))
                return render(request, 
                              'tracker/folders/add.html', 
                              {'form': form})

            return redirect('tracker:task_list', folder='without')
    else:
        form = FolderForm()

web/tracker/templates/tracker/planners/add.html
{% extends 'base.html' %}

{% block title %}Add planner{% endblock %}

{% block content %}
    <div class="text-indent">
    <h2 class="sub-header">Add planner</h2>
        <form method="POST">
            <table class="table">
            {% csrf_token %} {{ form }}
            </table>
            <button type="submit" class="btn btn-primary bottom-buttons" >Add</button>
        </form>
    </div>
{% endblock %}

web/tracker/templates/tracker/planners/edit.html
{% extends 'base.html' %}

{% block title %}Edit planner{% endblock %}

{% block content %}
    <div class="text-indent">
    <h2 class="sub-header">Edit planner</h2>
        <form method="POST">
            <table class="table">
            {% csrf_token %} {{ form }}
            </table>
            <button type="submit" class="btn btn-primary bottom-buttons" >Edit</button>
        </form>
    </div>
{% endblock %}

web/tracker/templates/tracker/planners/list.html
{% extends 'base.html' %}

{% block title %}Planners{% endblock %}

{% block content %}
    <div class="container-fluid">
        {% if planners %}
            <h2 class="sub-header">Planners list
                <div class='pull-right'>
                    <a href={% url 'tracker:planner_add' %} class='btn btn-info'>Add new</a>
                </div>
            </h2>
            <div class="table-responsive">
                <table class="table table-hover" data-toggle="table" data-sort-name="stargazers_count" data-sort-order="desc">
                    <thead>
                        <tr>
                            <th data-field="id_count" data-sortable="true" class="narrow-col">Id</th>
                            <th data-field="task_name" data-sortable="true">Task name</th>
                            <th>Last created time</th>
                            <th data-field="created_tasks_count" data-sortable="true">Created tasks count</th>
                            <th data-field="status" data-sortable="true">Status</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for planner in planners %}
                            <tr>
                                <td>{{ planner.id }}</td>
                                <td>{{ planner.task_template.name }}</td>
                                <td>
                                    {% if planner.last_created_time < planner.start_time %}
                                        None
                                    {% else %}
                                        {{ planner.last_created_time }}
                                    {% endif %}
                                </td>
                                <td>{{ planner.created_tasks_count }}</td>
                                <td>{{ planner.status }}</td>
                                <td>
                                    <a href={% url 'tracker:planner_show' planner_id=planner.id %} class='btn btn-info'>
                                        <span class="glyphicon glyphicon-eye-open"></span>
                                    </a>
                                    {% if planner.status != "FINISHED" %}
                                        <a href={% url 'tracker:planner_edit' planner_id=planner.id %} class='btn btn-default'>
                                            <span class="glyphicon glyphicon-pencil"></span>
                                        </a>
                                    {% endif %}
                                    <form style='display: inline-block;' action={% url 'tracker:planner_delete' planner_id=planner.id %} method='post'>
                                        {% csrf_token %}
                                        <button type='submit' class='btn btn-danger' onclick="return confirm('Do you really want to delete this planner?')">
                                            <span class="glyphicon glyphicon-trash"></span>
                                        </button>
                                    </form>
                                </td>
                            <tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        {% else %}
            <h2 class="sub-header">No planners
                <div class='pull-right'>
                    <a href={% url 'tracker:planner_add' %} class='btn btn-info'>Add new</a>
                </div>
            </h2>
        {% endif %}
    </div>
{% endblock %}

web/tracker/templates/tracker/planners/show.html
{% extends 'base.html' %}

{% block title %}Planner details{% endblock %}

{% block content %}
    <div class="container-fluid">
        <h2 class="sub-header">Planner details</h2>
        <div class="table-responsive">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th  colspan="2" class="col-sm-1">Field</th>
                        <th>Value</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td colspan="2">Id</td>
                        <td>{{ planner.id }}</td>
                    </tr>
                    <tr>
                        <td colspan="2">Interval type</td>
                        <td>{{ planner.interval_type }}</td>
                    </tr>
                    <tr>
                        <td colspan="2">Interval count</td>
                        <td>{{ planner.interval_count }}</td>
                    </tr>
                    <tr>
                        <td colspan="2">Start time</td>
                        <td>{{ planner.start_time }}</td>
                    </tr>
                    <tr>
                        <td colspan="2">End time</td>
                        <td>{{ planner.end_time }}</td>
                    </tr>
                    <tr>
                        <td colspan="2">Last created time</td>
                        <td>
                            {% if planner.last_created_time < planner.start_time %}
                                None
                            {% else %}
                                {{ planner.last_created_time }}
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">Created tasks count</td>
                        <td>{{ planner.created_tasks_count }}</td>
                    </tr>
                    <tr>
                        <td colspan="2">Total tasks count</td>
                        <td>{{ planner.total_tasks_count }}</td>
                    </tr>
                    <tr>
                        <td rowspan="7">Task template</td>
                        <td class="col-sm-1">Name</td>
                        <td>{{ planner.task_template.name }}</td>
                    <tr>
                    </tr>
                        <td class="col-sm-1">Start time</td>
                        <td>{{ planner.task_template.start_time }}</td>
                    </tr>
                    </tr>
                        <td class="col-sm-1">End time</td>
                        <td>{{ planner.task_template.end_time }}</td>
                    </tr>
                    </tr>
                        <td class="col-sm-1">Description</td>
                        <td>{{ planner.task_template.description|default:"None" }}</td>
                    </tr>
                    </tr>
                        <td class="col-sm-1">Priority</td>
                        <td>{{ planner.task_template.priority }}</td>
                    </tr>
                    </tr>
                        <td class="col-sm-1">Folder id</td>
                        <td>{{ planner.task_template.folder_id }}</td>
                    </tr>
                    <tr>
                        <td colspan="2">Created tasks (not deleted)</td>
                        <td>
                            {% if planner.created_tasks %}
                                {% for task, folder in task_folder_list %}
                                    <div>
                                        <a href={% url 'tracker:task_show' folder=folder task_id=task.id %}>
                                            Id: {{ task.id }}&emsp;Start time: {{ task.start_time }}
                                        </a>
                                    </div>
                                {% endfor %}
                            {% else %}
                                No tasks
                            {% endif %}
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div>
            <div class="pull-left bottom-buttons">
                {% if planner.status != "FINISHED" %}
                    <a href={% url 'tracker:planner_edit' planner_id=planner.id %} class='btn btn-default'>Edit</a>
                {% endif %}
            </div>
            <div class="pull-right">
                <form style='display: inline-block;' action={% url 'tracker:planner_delete' planner_id=planner.id %} method='post'>
                    {% csrf_token %}
                    <button type='submit' class='btn btn-danger' onclick="return confirm('Do you really want to delete this planner?')">Delete</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}