web/tracker/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from . import views

app_name = "tracker"

task_fields_patterns = [
    url(r'^executor/add/$', views.add_executor, name='executor_add'),
    url(r'^executor/(?P<executor_id>\d+)/delete/$', views.delete_executor, name='executor_delete'),

    url(r'^notification/add/$', views.add_notification, name='notification_add'),
    url(r'^notification/(?P<notification_id>\d+)/delete/$', views.delete_notification, name='notification_delete'),

    url(r'^tag/add/$', views.add_tag, name='tag_add'),
    url(r'^tag/(?P<tag_id>\d+)/delete/$', views.delete_task_tag, name='task_tag_delete'),

    url(r'^subtask/attach/$', views.attach_subtask, name='subtask_attach'),
    url(r'^subtask/(?P<subtask_id>\d+)/detach/$', views.detach_subtask, name='subtask_detach'),
]

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^users/singup/$', views.signup, name='signup'),
    url(r'^users/login/$', auth_views.login, name='login'),
    url(r'^users/logout/$', auth_views.logout, {'template_name': 'registration/logout.html'}, name='logout'),

    url(r'^search/task/$', views.search_task, name='task_search'),

    url(r'^tag/(?P<tag_id>\d+)/show/$', views.show_tag, name='tag_show'),
    url(r'^tag/(?P<tag_id>\d+)/edit/$', views.edit_tag, name='tag_edit'),
    url(r'^tag/(?P<tag_id>\d+)/delete/$', views.delete_tag, name='tag_delete'),

    url(r'^folder/add/$', views.add_folder, name='folder_add'),
    url(r'^folder/(?P<folder_id>[0-9]+)/edit/$', views.edit_folder, name='folder_edit'),
    url(r'^folder/(?P<folder_id>[0-9]+)/delete/$', views.delete_folder, name='folder_delete'),

    url(r'^planner/list/$', views.planner_list, name='planner_list'),
    url(r'^planner/add/$', views.add_planner, name='planner_add'),
    url(r'^planner/(?P<planner_id>[0-9]+)/delete/$', views.delete_planner, name='planner_delete'),
    url(r'^planner/(?P<planner_id>[0-9]+)/edit/$', views.edit_planner, name='planner_edit'),
    url(r'^planner/(?P<planner_id>[0-9]+)/show/$', views.show_planner, name='planner_show'),

    url(r'^folder/(?P<folder>[a-z0-9]+)/task/list/$', views.list_task, name='task_list'),
    url(r'^folder/(?P<folder>[a-z0-9]+)/task/add/$', views.add_task, name='task_add'),
    url(r'^folder/(?P<folder>[a-z0-9]+)/task/(?P<task_id>\d+)/', include(task_fields_patterns)),
    url(r'^folder/(?P<folder>[a-z0-9]+)/task/(?P<task_id>\d+)/edit/$', views.edit_task, name='task_edit'),
    url(r'^folder/(?P<folder>[a-z0-9]+)/task/(?P<task_id>\d+)/show/$', views.show_task, name='task_show'),
    url(r'^folder/(?P<folder>[a-z0-9]+)/task/(?P<task_id>\d+)/delete/$', views.delete_task, name='task_delete'),
    url(r'^folder/(?P<folder>[a-z0-9]+)/task/(?P<task_id>\d+)/complete/$', views.complete_task, name='task_complete'),
]

web/web/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('tracker.urls')),
]

web/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <meta name="viewport" content="width=device-width, minimum-scale=1.0 minimal-ui"/>
        <meta name="description" content=""/>
        <meta name="author" content=""/>

        <title>{% block title %}Python tracker{% endblock %}</title>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.0/bootstrap-table.min.js"></script>
        <script type="text/javascript" src="//code.jquery.com/jquery-2.1.1.js"></script>
        <script type="text/javascript" src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
        <link href="https://fonts.googleapis.com/css?family=Spectral" rel="stylesheet"> 
        <link rel="stylesheet" type="text/css" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'base.css' %}" />

        {% block head %}{% endblock %}
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href={% url 'tracker:home' %}>Python tracker</a>
                </div>
                <div class="navbar-collapse collapse">
                    {% if user.is_authenticated %}
                        <ul class="nav navbar-nav">
                            <li><a href={% url 'tracker:task_list' folder='without' %}>Tasks</a></li>
                            <li><a href={% url 'tracker:planner_list' %}>Planners</a></li>
                            <li><a href={% url 'tracker:task_search' %}>Search</a></li>    
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            <li>
                            {% if user.is_authenticated %}
                                <a href="" class="link-disabled"><span class="glyphicon glyphicon-user"></span> {{ user.username }}</a>
                            {% endif %}
                            </li>
                            <li><a href={% url 'tracker:logout' %}>Logout</a></li>
                        </ul>
                    {% else %}
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href={% url 'tracker:login' %}>Login</a></li>
                            <li><a href={% url 'tracker:signup' %}>Register</a></li>
                        </ul>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="container">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-info alert-size {{ message.tags }}">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <center>{{ message }}</center>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
        {% block content %}{% endblock %}
    </body>
</html>